### ISSUE TITLE
Hangs at startup first time running

### ISSUE THREAD

**Issue by mitchell486** [hangoutsbot/hangoutsbot#681]
When I start this, it attempts to start but then constantly loops with the following after I manually installed "pip install telegram".

> 18:33:11 INFO root: bot initialised
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telepot/async/__init__.py", line 343, in get_from_telegram_server
    result = yield from self.getUpdates(offset=offset, timeout=20)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telepot/async/__init__.py", line 266, in getUpdates
    data=_rectify(p)))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telepot/async/__init__.py", line 59, in _post
    raise TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Not Found', 404, {'description': 'Not Found', 'ok': False, 'error_code': 404})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telepot/async/__init__.py", line 343, in get_from_telegram_server
    result = yield from self.getUpdates(offset=offset, timeout=20)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telepot/async/__init__.py", line 266, in getUpdates
    data=_rectify(p)))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telepot/async/__init__.py", line 59, in _post
    raise TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Not Found', 404, {'description': 'Not Found', 'ok': False, 'error_code': 404})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telepot/async/__init__.py", line 343, in get_from_telegram_server
    result = yield from self.getUpdates(offset=offset, timeout=20)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telepot/async/__init__.py", line 266, in getUpdates
    data=_rectify(p)))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telepot/async/__init__.py", line 59, in _post
    raise TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Not Found', 404, {'description': 'Not Found', 'ok': False, 'error_code': 404})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telepot/async/__init__.py", line 343, in get_from_telegram_server
    result = yield from self.getUpdates(offset=offset, timeout=20)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telepot/async/__init__.py", line 266, in getUpdates
    data=_rectify(p)))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/telepot/async/__init__.py", line 59, in _post
    raise TelegramError(description, error_code, data)

**Comment by mitchell486** [comment]
I believe I have fixed this with 'pip install telepot --upgrade'. I am closing this. Thank you.

**Comment by nylonee** [comment]
`pip install telepot --upgrade` does not fix the issue, as this updates telepot to the latest version which is incompatible with the current telesync.

Pasting my errors here: 
```
02:41:08 ERROR asyncio: Task exception was never retrieved
future: <Task finished coro=<TelegramBot.setup_bot_info() done, defined at /usr/local/share/hangoutsbot/hangupsbot/plugins/telesync/__init__.py:47> exception=TelegramError('Not Found', 404, {'ok': False, 'error_code': 404, 'description': 'Not Found'})>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/share/hangoutsbot/hangupsbot/plugins/telesync/__init__.py", line 50, in setup_bot_info
    _bot_data = yield from self.getMe()
  File "/usr/local/share/hangoutsbot/venv/lib/python3.5/site-packages/telepot/async/__init__.py", line 82, in getMe
    return (yield from _post(self._methodurl('getMe'), self._http_timeout))
  File "/usr/local/share/hangoutsbot/venv/lib/python3.5/site-packages/telepot/async/__init__.py", line 59, in _post
    raise TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Not Found', 404, {'ok': False, 'error_code': 404, 'description': 'Not Found'})
Traceback (most recent call last):
  File "/usr/local/share/hangoutsbot/venv/lib/python3.5/site-packages/telepot/async/__init__.py", line 343, in get_from_telegram_server
    result = yield from self.getUpdates(offset=offset, timeout=20)
  File "/usr/local/share/hangoutsbot/venv/lib/python3.5/site-packages/telepot/async/__init__.py", line 266, in getUpdates
    data=_rectify(p)))
  File "/usr/local/share/hangoutsbot/venv/lib/python3.5/site-packages/telepot/async/__init__.py", line 59, in _post
    raise TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Not Found', 404, {'ok': False, 'error_code': 404, 'description': 'Not Found'})
```

With the last error running forever

**Comment by nylonee** [comment]
@gurumadmat Note

**Comment by gurumadmat** [comment]
I guess installing telepot == 7.1 should do the trick.

**Comment by nylonee** [comment]
Forgot to clarify, this error happens even on telepot==7.1.

I tagged the wrong person just now, sorry gurumadmat :P 

@makiftasova Take note
