### ISSUE TITLE
[v3] [plugins] [slackrtm] compatibility

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#765]
Getting this when I attempt to load the slackrtm plugin on v3:

```
20:37:01 ERROR plugins.slackrtm: SlackRTMThread: unhandled exception: module 'hangups_shim' has no attribute 'ui'
Traceback (most recent call last):
  File "/usr/local/share/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 1297, in run
    self._listener = SlackRTM(self._config, self._bot, self._loop, threaded=True)
  File "/usr/local/share/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 348, in __init__
    name = hangups.ui.utils.get_conv_name(c, truncate=True)
AttributeError: module 'hangups_shim' has no attribute 'ui'
```

**Comment by endofline** [comment]
* don't use ui components from hangups - that's part of the example client
* replace 'hangups.ui.utils.get_conv_name' with [bot.conversations.get_name](https://github.com/hangoutsbot/hangoutsbot/wiki/Permanent-Memory#conversation_titles)

**Comment by endofline** [comment]
on the bright side it appears that this is the sole plugin that uses 'hangups.ui' ;p

**Comment by nylonee** [comment]
Fixed in 943f83c65c8adec0c16cbd1aefa78955bd47012c, to be closed manually upon merge into master

**Comment by endofline** [comment]
please test plugins thoroughly before a staging merge

**Comment by OllieTerrance** [comment]
Having applied this patch, I'm still getting more issues:

```
ERROR plugins.slackrtm: SlackRTMThread: unhandled exception: 'conversation_id' object has no attribute 'id'
Traceback (most recent call last):
  File "hangoutsbot/hangupsbot/plugins/slackrtm.py", line 1296, in run
    self._listener = SlackRTM(self._config, self._bot, self._loop, threaded=True)
  File "hangoutsbot/hangupsbot/plugins/slackrtm.py", line 347, in __init__
    name = self.bot.conversations.get_name(c, truncate=True)
  File "hangoutsbot/hangupsbot/permamem.py", line 596, in get_name
    convid = conv.id_
  File "hangoutsbot/venv/lib/python3.6/site-packages/hangups/conversation.py", line 190, in id_
    return self._conversation.conversation_id.id
AttributeError: 'conversation_id' object has no attribute 'id'
```

Not sure where the `conversation_id` comes in here, it's not the usual hangups conversation ID.  Are we mocking the conversation object?  If so, looks like it fails because the `id` attribute is called `id_` instead.

Usual types are `hangups.hangouts_pb2.Conversation`, `hangups.hangouts_pb2.ConversationId`, but after throwing some logging in, it looks like SlackRTM is here using `hangups_conversation.client_conversation`, `hangups_conversation.conversation_id` instead.
